baseurl = "https://gophersaurus.github.io/docs/"
languageCode = "en-us"
title = "Gophersaurus"
theme = "gophersaurus"

DisableRSS = true
DisableSitemap = true

copyright = "Copyright (c) 2015, Jack Spirou; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Jack Spirou"
