baseurl = "https://gophersaurus.github.io/docs/"
canonifyurls = true
languageCode = "en-us"
title = "Gophersaurus Framework"
theme = "gophersaurus"

DisableRSS = true
DisableSitemap = true

copyright = "Copyright (c) 2015, Jack Spirou; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Jack Spirou"

[indexes]
	tag = "tags"
	group = "groups"

[[menu.main]]
	name = "Prologue"
	weight = 1

[[menu.main]]
	name = "Setup"
	weight = 2

[[menu.main]]
	name = "Basics"
	weight = 3

[[menu.main]]
	name = "Architecture"
	weight = 4

[[menu.main]]
	name = "Services"
	weight = 5

[[menu.main]]
	name = "Database Admin"
	weight = 6
