# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "gophersaurus"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.01

[author]
  name = "Jack Spirou"
  homepage = "github.com/jackspirou"

# If porting an existing theme
[original]
  name = "Larvel"
  homepage = "https://larvel.com"
  repo = "github.com/laravel/docs"
